### PR TITLE
Add Voting Table, NetworkContext Fix

### LINKED ISSUE #68: Type Mismatch In Setting Default Network Context
Getting the default network without going through the networkSwitcher currently catches the '1' string set in the second condition of the following
```  
  const [currentNetwork, setCurrentNetwork] = useState(
    window.localStorage.getItem('defaultNetwork') || '1'
  );
```

This prevents the etherscan selector from working as it uses integers in its comparisons:
  ```
  useEffect(() => {
    if (currentNetwork){
      if(currentNetwork === 1){
          setTxLink("https://etherscan.io/")
      }
      else if(currentNetwork === 4){
          setTxLink("https://rinkeby.etherscan.io/")
      }
    }
  },[currentNetwork]);
```

Currently this is just routing users to https://www.tellorscan.com/undefined{address}

### PR DESCRIPTION
**Pull request by imaginebeingatcomputers**
Added vote table to per dispute nested table:
image

Fixes #68

### CODE REVIEW

**Comment by bennisan86** [comment]
Nice, thx for this! Good job! I think it would be ideal if we could adjust the design as following:
- Hide this table behind a collapse expand, with the 'Total votes' being the trigger for this expand. Important that we only do this when we do have votes, and not have an empty table there when there are no votes
Screenshot 2021-06-11 at 13 54 10
- Style the table similar to other tables use in tellorscan (see screenshot below):
  - changing the header-items (Date, Voter, ...) to lower case: date, voter
  - truncating the address of the voter
  - adjusting the css to have similar paddings/height/colours as other tables
 
Screenshot 2021-06-11 at 13 55 11

**Comment by imaginebeingatcomputers** [comment]
Finished with the styling fixes:

image

image

**Comment by bennisan86** [comment]
Awesome work @imaginebeingatcomputers ,we're almost there! Two minors things:
-  can you give it the same padding as the other tables?
- I noticed the ">" from past disputes now sticks out. That should be in its original place :)

Thanks in advance !

**Comment by imaginebeingatcomputers** [comment]
Updated and fixed #70

**Comment by imaginebeingatcomputers** [comment]
fixes #71

**Comment by imaginebeingatcomputers** [comment]
Updated screenshot showing the padding update, fix to Passed/Closed logic, and sorting

image

**Comment by bennisan86** [comment]
There was still a small change I wanted regarding the paddings but I'll merge the PR and do that myself, I think that sort of fuddling around might need a designers eye :). Thanks for the work @imaginebeingatcomputers !

**Pull request merged**
